language: node_js
node_js:
  - 7
  - 8
  - 9
cache:
  yarn: true
  directories:
    - public/components
before_install:
  - yarn global add bower codecov istanbul
install: 
  - yarn
  - bower install
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov
  - yarn run lint
  - yarn run posttest
notifications:
    slack:
      rooms: 
        - araytek:B8Xevy6shC51ftn3tBiZR8fw
      on_success: change
      on_failure: always